### ISSUE TITLE
Web Browser Communication

### ISSUE THREAD

**Issue by ghost** [MartinKondor/TinyChat#1]
I came across this development in my attempt to think of a simple chat server, and I was wondering because of the IP address that is used by the PI (which I think would be cool to have an automatic fill for that) if people could access the chat via browser? Like how for some applications (ex. Protonmail) there is the online version as well as the desktop edition.

**Comment by MartinKondor** [comment]
Autofilling is already implemented. I will start to work on a browser based version.
